options:
  cache-config: false
  merge-default-rules: false
  formatter: stylish

files:
  include:
    - '**/*.s+(a|c)ss'
  ignore:
    - 'node_modules/**/*'
    - 'src/assets/styles/vendor/**/*'

rules:
  # Reports when you use improper spacing around ! (the "bang") in !important and !default declarations.
  space-before-bang:
    - 2
    - include: true
  space-after-bang:
    - 2
    - include: false

  # Prefer border: 0 over border: none.
  border-zero: 2

  # Prefer hexadecimal color codes over color keywords
  no-color-keywords: 2

  # Prefer // comments over /* ... */
  no-css-comments: 2

  # Reports !debug statements
  no-debug: 1

  # Forces Extend, Mixins with no content, properties, mixins with content, nested rules
  extends-before-declarations: 2
  mixins-before-declarations: 0
  extends-before-mixins: 2

  # Prevent duplicate properties
  no-duplicate-properties: 2

  # Separate rule, function, and mixin declarations with empty lines.
  empty-line-between-blocks:
    - 2
    - ignore-single-line-rulesets: true

  # Reports when you have an empty rule set.
  no-empty-rulesets: 2

  # Files should always have a final newline.
  final-newline:
    - 2
    - include: true

  # Specifies whether you prefer shorthand or long-form hexadecimal colors by setting the style option to short or long, respectively.
  hex-length:
    - 2
    - style: short

  # Checks if hexadecimal colors are written in lowercase.
  hex-notation:
    - 2
    - style: lowercase

  # Ensure hexadecimal colors are valid
  no-invalid-hex: 2

  # The basenames of @imported SCSS partials should not begin with an underscore and should not include the filename extension
  clean-import-paths:
    - 2
    - filename-extension: false
      leading-underscore: false

  # Use two spaces per indentation level.
  indentation:
    - 2
    - size: 2

  # Write leading zeros for numeric values with a decimal point.
  leading-zero:
    - 2
    - include: true

  # Reports when you define the same selector twice in a single sheet.
  no-mergeable-selectors: 1

  # Functions, mixins, and variables should be declared with all lowercase letters and hyphens instead of underscores.
  mixin-name-format:
    - 2
    - convention: hyphenatedlowercase
  placeholder-name-format:
    - 2
    - convention: hyphenatedlowercase
  variable-name-format:
    - 2
    - convention: hyphenatedlowercase
  function-name-format:
    - 2
    - convention: hyphenatedlowercase
  # It is good practice to choose a convention for naming selectors.
  id-name-format:
    - 2
    - convention: hyphenatedlowercase
  class-name-format:
    - 0
    - convention: hyphenatedlowercase

  # Always use placeholder selectors in @extend.
  placeholder-in-extend: 2

  # Sort properties in a strict order.
  # Using RECESS order (https://github.com/twitter/recess/blob/master/lib/lint/strict-property-order.js#L36)
  property-sort-order:
    - 2
    - ignore-custom-properties: false
      order:
        - position
        - top
        - right
        - bottom
        - left
        - z-index
        - display
        - float
        - width
        - height
        - max-width
        - max-height
        - min-width
        - min-height
        - padding
        - padding-top
        - padding-right
        - padding-bottom
        - padding-left
        - margin
        - margin-top
        - margin-right
        - margin-bottom
        - margin-left
        - margin-collapse
        - margin-top-collapse
        - margin-right-collapse
        - margin-bottom-collapse
        - margin-left-collapse
        - overflow
        - overflow-x
        - overflow-y
        - clip
        - clear
        - font
        - font-family
        - font-size
        - font-smoothing
        - osx-font-smoothing
        - font-style
        - font-weight
        - hyphens
        - src
        - line-height
        - letter-spacing
        - word-spacing
        - color
        - text-align
        - text-decoration
        - text-indent
        - text-overflow
        - text-rendering
        - text-size-adjust
        - text-shadow
        - text-transform
        - word-break
        - word-wrap
        - white-space
        - vertical-align
        - list-style
        - list-style-type
        - list-style-position
        - list-style-image
        - pointer-events
        - cursor
        - background
        - background-attachment
        - background-color
        - background-image
        - background-position
        - background-repeat
        - background-size
        - border
        - border-collapse
        - border-top
        - border-right
        - border-bottom
        - border-left
        - border-color
        - border-image
        - border-top-color
        - border-right-color
        - border-bottom-color
        - border-left-color
        - border-spacing
        - border-style
        - border-top-style
        - border-right-style
        - border-bottom-style
        - border-left-style
        - border-width
        - border-top-width
        - border-right-width
        - border-bottom-width
        - border-left-width
        - border-radius
        - border-top-right-radius
        - border-bottom-right-radius
        - border-bottom-left-radius
        - border-top-left-radius
        - border-radius-topright
        - border-radius-bottomright
        - border-radius-bottomleft
        - border-radius-topleft
        - content
        - quotes
        - outline
        - outline-offset
        - opacity
        - filter
        - visibility
        - size
        - zoom
        - transform
        - box-align
        - box-flex
        - box-orient
        - box-pack
        - box-shadow
        - box-sizing
        - table-layout
        - animation
        - animation-delay
        - animation-duration
        - animation-iteration-count
        - animation-name
        - animation-play-state
        - animation-timing-function
        - animation-fill-mode
        - transition
        - transition-delay
        - transition-duration
        - transition-property
        - transition-timing-function
        - background-clip
        - backface-visibility
        - resize
        - appearance
        - user-select
        - interpolation-mode
        - direction
        - marks
        - page
        - set-link-source
        - unicode-bidi
        - speak

  # Reports when you use an unknown CSS property
  no-misspelled-properties: 0

  # Avoid qualifying elements in selectors
  no-qualifying-elements:
    - 2
    - allow-element-with-attribute: true
      allow-element-with-class: false
      allow-element-with-id: false

  # Don't write selectors with a depth of applicability greater than 3.
  bem-depth:
    - 2
    - max-depth: 3

  # Prefer the shortest shorthand form possible for properties that support it.
  shorthand-values: 2

  # Properties within rule sets should each reside on their own line.
  brace-style:
    - 2
    - style: 1tbs
    - allow-single-line: false

  # Split selectors onto separate lines after each comma.
  single-line-per-selector: 2

  # Commas in lists should be followed by a space.
  space-after-comma: 2

  # Properties should be formatted with a single space separating the colon from the property's value.
  space-after-colon:
    - 2
    - include: true

  # Properties should be formatted with no space between the name and the colon.
  space-before-colon:
  - include: false

  # Opening braces should be preceded by a single space.
  space-before-brace:
    - 2
    - include: true

  # Parentheses should not be padded with spaces.
  space-between-parens:
    - 2
    - include: false

  # String literals should be written with single quotes unless using double quotes would save on escape characters.
  quotes:
    - 2
    - style: single

  # Property values; @extend, @include, and @import directives; and variable declarations should always end with a semicolon.
  trailing-semicolon: 2

  # Don't write trailing zeros for numeric values with a decimal point.
  no-trailing-zero: 2

  # URLs should not contain domains
  no-url-domains: 0

  # URLs should not contain protocols
  no-url-protocols:
    - 2
    - allow-protocol-relative-urls: true

  # URLs should always be enclosed within quotes.
  url-quotes: 2

  # Avoid vendor prefixes. That is, don't write them yourself.
  no-vendor-prefixes:
    - 0
    -
      'excluded-identifiers':
        - 'ms'
        - 'webkit'
        - 'moz'

  # Omit length units on zero values.
  zero-unit: 2
